# Generated by Django 5.0 on 2023-12-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_patient_email_remove_patient_medical_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=10),
        ),
    ]
