# Generated by Django 5.0 on 2023-12-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_patient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
